name: Release & Publish to NPM
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select the version type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Init Git user
        run: |
          git config --global user.email "brantalikp@gmail.com"
          git config --global user.name "BrantalikP"
      - name: Init the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run release
        run: yarn release --${{ github.event.inputs.version }} --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
